// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/tagger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tagger_Tag_FullMethodName = "/tagger.Tagger/Tag"
)

// TaggerClient is the client API for Tagger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для обработки запросов
type TaggerClient interface {
	// Метод для присвоения тегов фильму
	Tag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*TagsReply, error)
}

type taggerClient struct {
	cc grpc.ClientConnInterface
}

func NewTaggerClient(cc grpc.ClientConnInterface) TaggerClient {
	return &taggerClient{cc}
}

func (c *taggerClient) Tag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*TagsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagsReply)
	err := c.cc.Invoke(ctx, Tagger_Tag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaggerServer is the server API for Tagger service.
// All implementations must embed UnimplementedTaggerServer
// for forward compatibility.
//
// Сервис для обработки запросов
type TaggerServer interface {
	// Метод для присвоения тегов фильму
	Tag(context.Context, *TagRequest) (*TagsReply, error)
	mustEmbedUnimplementedTaggerServer()
}

// UnimplementedTaggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaggerServer struct{}

func (UnimplementedTaggerServer) Tag(context.Context, *TagRequest) (*TagsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tag not implemented")
}
func (UnimplementedTaggerServer) mustEmbedUnimplementedTaggerServer() {}
func (UnimplementedTaggerServer) testEmbeddedByValue()                {}

// UnsafeTaggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaggerServer will
// result in compilation errors.
type UnsafeTaggerServer interface {
	mustEmbedUnimplementedTaggerServer()
}

func RegisterTaggerServer(s grpc.ServiceRegistrar, srv TaggerServer) {
	// If the following call pancis, it indicates UnimplementedTaggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tagger_ServiceDesc, srv)
}

func _Tagger_Tag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaggerServer).Tag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tagger_Tag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaggerServer).Tag(ctx, req.(*TagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tagger_ServiceDesc is the grpc.ServiceDesc for Tagger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tagger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tagger.Tagger",
	HandlerType: (*TaggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tag",
			Handler:    _Tagger_Tag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tagger.proto",
}
