# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tagger_pb2 as tagger__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in tagger_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TaggerStub(object):
    """Сервис для обработки запросов"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tag = channel.unary_unary(
            "/tagger.Tagger/Tag",
            request_serializer=tagger__pb2.TagRequest.SerializeToString,
            response_deserializer=tagger__pb2.TagsReply.FromString,
            _registered_method=True,
        )


class TaggerServicer(object):
    """Сервис для обработки запросов"""

    def Tag(self, request, context):
        """Метод для присвоения тегов фильму"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TaggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Tag": grpc.unary_unary_rpc_method_handler(
            servicer.Tag,
            request_deserializer=tagger__pb2.TagRequest.FromString,
            response_serializer=tagger__pb2.TagsReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tagger.Tagger", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("tagger.Tagger", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Tagger(object):
    """Сервис для обработки запросов"""

    @staticmethod
    def Tag(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tagger.Tagger/Tag",
            tagger__pb2.TagRequest.SerializeToString,
            tagger__pb2.TagsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
